version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: lexicadb
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PWD
    volumes:
      - lexicadb:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  lexicadb:
